### PR TITLE
Update inputmethod.py3

### PR DESCRIPTION
**Pull request by dingdang66686**
Convert i to int, so it can be compared with the index of input method.

### CODE REVIEW

**Comment by trmdi** [comment]
This line is wrong syntax too, could you also fix it?
https://github.com/openSUSE-zh/systemd-inputmethod-generator/blob/de80b584681a80c47343b1113c0c48cc162a856f/inputmethod.py3#L13

btw, ping @marguerite !

**Comment by dingdang66686** [comment]
> This line is wrong syntax too, could you also fix it?
> 
> https://github.com/openSUSE-zh/systemd-inputmethod-generator/blob/de80b584681a80c47343b1113c0c48cc162a856f/inputmethod.py3#L13
> 
> btw, ping @marguerite !

I have changed the && opetrator to 'and'. Do you mean it? @trmdi

**Comment by trmdi** [comment]
Yes, thank you!

**Comment by trmdi** [comment]
@marguerite Could you bump the version and update the OBS package? Currently the script stops working.

**Comment by trmdi** [comment]
@marguerite Thank you for doing that so quickly.
Btw, I've just learnt this command can get a more lightweight tarball:
> wget https://github.com/openSUSE-zh/systemd-inputmethod-generator/tarball/master -O systemd-inputmethod-generator-1.0.5.tar.gz

**Pull request merged**
